### ISSUE TITLE
cant log on

### ISSUE THREAD

**Issue by Clickba1t** [dtube/DTubeGo#137]
When i try to log on the app is just spinning on searching for best node... What do I do wrong?

**Comment by tibfox** [comment]
Did you have entered your dtube user and private key? I have seen people
trying to login with their hive/steem data before which is not working. I
did not implemented a correct error handling in that case. That's on the
list.

Clickba1t ***@***.***> schrieb am Sa., 16. Okt. 2021, 17:31:

**Comment by Clickba1t** [comment]
What are the timeframe on the firebase login btw?

**Comment by tibfox** [comment]
glad you solved it on your own :) 
We had a leader discussion lately with a working prototype so it can't take very long. Unfortunately I can not tell you a specific timeframe right now since I am not responsible for this part of development.
