### ISSUE TITLE
ios app crash when recording a moment

### ISSUE THREAD

**Issue by tibfox** [dtube/DTubeGo#165]
iPhone XR - sent bug report, app crashes as soon as I click button to record a moment

**Comment by sag333ar** [comment]
Hey @tibfox 
Here is a easy quick reproducible video

https://user-images.githubusercontent.com/4737312/142893246-6b6c7c1c-a58f-45f8-9ec2-bdf8fc5e87ef.mov

.

**Comment by sag333ar** [comment]
Found root cause after debugging the app on iOS Device.

Here is the Error.

```
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an `NSMicrophoneUsageDescription` key with a string value explaining to the user how the app uses this data.
```

Fixing it & raising PR.
