### ISSUE TITLE
App crash when saving profile settings 

### ISSUE THREAD

**Issue by tibfox** [dtube/DTubeGo#168]

**Comment by tibfox** [comment]
![tempFileForShare_20211122-225152.jpg](https://user-images.githubusercontent.com/6019754/142944305-7f9b6949-bcab-4e32-8886-b4dfce9349e2.jpg)

**Comment by brishtiteveja** [comment]
Also on my iphone with the test app, profile page and videos are not showing up.. The error says "null check operator used on a null value".. may be an extra check for null is missing.

**Comment by tibfox** [comment]
@brishtiteveja that's a different error. Here is saving the profile mentioned. Can you please open a separate issue for that and share a screenshot please.  I will check that tomorrow

**Comment by sag333ar** [comment]
Hi @tibfox , I know you wanted me to look into this but I couldn't because I encountered this issue.
https://github.com/dtube/DTubeGo/issues/176
