### ISSUE TITLE
Profile page shows error on iOS platform

### ISSUE THREAD

**Issue by brishtiteveja** [dtube/DTubeGo#170]
On some iphone device, profile is not being shown upon clicking because of a null check error.

The exact error message "Null check operator used on a null value
![2021-11-22](https://user-images.githubusercontent.com/2281405/142954416-935ee7da-2b79-48c4-be55-eac7e0c90633.jpeg)
"

**Comment by tibfox** [comment]
that should be reproducable by: 
going in search: 
![grafik](https://user-images.githubusercontent.com/6019754/142999456-a1dcd487-58f7-45ea-9350-48bac0141494.png)

searching for brish and clicking the first entry:
![grafik](https://user-images.githubusercontent.com/6019754/142999592-96295f8a-688f-4161-a3a7-b590f15ef9f2.png)

**Comment by tibfox** [comment]
fixed in dev branch
