### ISSUE TITLE
Balance displays wrong in user search

### ISSUE THREAD

**Issue by skzap** [dtube/DTubeGo#173]
Try searching for 'itsdevdc', it indicates 139.31 KDTC, while the user actually only has 139.31 DTC.

**Comment by skzap** [comment]
(scared me for a moment)

**Comment by tibfox** [comment]
@skzap  that's actually an issue of our search api... long time no indexing results in wrong values ;) it works usually

**Comment by DevDeckardCain** [comment]
Why so scared? Isn't it secure?
