### ISSUE TITLE
History screen has UI rendering issues

### ISSUE THREAD

**Issue by sag333ar** [dtube/DTubeGo#174]
![IMG_2528](https://user-images.githubusercontent.com/4737312/143076926-15d56c7d-0e14-4bd5-a26c-d3af7f81fa73.PNG)
![IMG_2529](https://user-images.githubusercontent.com/4737312/143076948-050fe9fe-3add-4072-917c-7004b934617a.PNG)

**Comment by tibfox** [comment]
fixed in dev branch
