### ISSUE TITLE
Status bar not visible on some screens.

### ISSUE THREAD

**Issue by sag333ar** [dtube/DTubeGo#178]
![status-bar-not-visible-2](https://user-images.githubusercontent.com/4737312/143078046-ea3a351b-b0eb-447b-9d00-afead193176e.png)

on History page, status bar is clearly visible.

but on videos feed page it is not.
![status-bar-not-visible](https://user-images.githubusercontent.com/4737312/143078108-6152ea45-187b-42b9-9b46-51c6f42bf8d9.png)

**Comment by tibfox** [comment]
fixed with d8644523d7c34e34cd0031404778c8f14d9ac5ec

**Comment by tibfox** [comment]
fixed in dev branch
