### ISSUE TITLE
iOS user can't log in

### ISSUE THREAD

**Issue by sag333ar** [dtube/DTubeGo#182]
https://user-images.githubusercontent.com/4737312/143262602-b153a173-a632-43dd-a255-e00fd4553343.mov

**Comment by tibfox** [comment]
please adds more details @sag333ar is that your account? is it a custom key?

**Comment by tibfox** [comment]
4iaxj on dtube. Only had the issue on initial login fopr 5 minutes. autologin works fine now 
-> closed until next user has the tsame issue
