### ISSUE TITLE
Video playback issues

### ISSUE THREAD

**Issue by tibfox** [dtube/DTubeGo#234]
If you Play a video and you switch to the moment section, both vidéos Will play.

**Comment by brishtiteveja** [comment]
yeah, this has been pretty annoying from personal experience. You will possibly have to stop the video with a hook before switching. So, switching tab should trigger some cleanup which is not happening right now.

**Comment by tibfox** [comment]
not reproducable anymore. the video is being stopped because it is not in focus anymore. We have a visibility detector going inside the feed which automaticaly stops videos when they are not visible anymore. The video itself will not get disposed (which is a good thing) and can get played back when the user switches back to the feed page. I fixed this visiblity detector recently so I think this is closed with this change as well.
