### ISSUE TITLE
ios build/compilation issue

### ISSUE THREAD

**Issue by brishtiteveja** [dtube/DTubeGo#55]
Various build issue with ios. Couldn't compile on a iphone with software version 14.7.1. In earlier ios version, I could once compile (test app on ios: https://drive.google.com/file/d/1ofbc4s-fC2sISf-Fp7aQ-OZQh19s2IhD/view?usp=drivesdk)

On my xcode.. for some pods.. it recommends to update the deployment target to be 12.0.. however it causes issue eventually
![Uploading Screen Shot 2021-08-03 at 2.01.43 PM.png…]

Another common issue with the youtube_explode_dart which needs to be downgraded to 1.9.6 for ios on pubspec.yaml 
<img width="1334" alt="Screen Shot 2021-08-03 at 2 03 06 PM" src="https://user-images.githubusercontent.com/2281405/128071573-8ab1548f-69ff-4bb6-83a2-c958fcf32f7c.png">

Some other debugging screenshots for future debugging.
<img width="1037" alt="Screen Shot 2021-08-03 at 2 04 22 PM" src="https://user-images.githubusercontent.com/2281405/128071708-41755954-5400-4ff6-ac7b-340f46f23444.png">
<img width="1032" alt="Screen Shot 2021-08-03 at 2 04 58 PM" src="https://user-images.githubusercontent.com/2281405/128071764-23937864-0f48-4ccf-98e7-4ca81096d8a5.png">

**Comment by tibfox** [comment]
@sag333ar fixed that
